### ISSUE TITLE
The script for step 4 will occur "Out of memory"

### ISSUE THREAD

**Issue by mnrkbys** [SentineLabs/AlphaGolang#4]
Hi, thanks for releasing great scripts.
I'm trying to analyze oRAT which has a hash value of 9b4717505d8d165b0b12c6e2b9cc4f58ee8095a6 (Yes, it's introduced in SentinelLabs' blog https://www.sentinelone.com/blog/from-the-front-lines-unsigned-macos-orat-malware-gambles-for-the-win/).

However, step 3 script does not work. Folders are not created.
Also, step 4 script will occur "Out of memory" error like below.
![スクリーンショット 2022-10-25 16 38 55](https://user-images.githubusercontent.com/26597618/197715004-2921c2bb-b589-4661-acbf-ac8f207d1f93.png)

I'm using IDA Pro 8.1.
Is there any solution to this problem?

**Comment by mnrkbys** [comment]
The script in step 3 was working fine. It's my mistake. I'm sorry.
However, the error in the script in step 4 remains.

**Comment by juanandresgs** [comment]
Hey! No worries, I had a feeling about Step3 ;)

Checking out Step 4 issue, any chance you're running on a VM w low RAM? I just ran Step4 on your sample with no issue.
If I'm completely honest, Step4 is the script that needs the most work and could probably use a full refactor.

**Comment by mnrkbys** [comment]
Aah! You are right!
I had completely forgotten that I had set the VM to a low amount of memory.
There was nothing wrong with your scripts.
Thanks for your reply!
